#!/bin/sh

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $dir

# startup neo4j and mongo
ttab -t 'shindig-android-prod' eval "\
MONGO_URL=mongodb://mongo:[PASSWORD]@[IP]:27017/shindig-app \
meteor run android-device --settings deploy/settings.json --mobile-server http://findashindig.com"
