#!/bin/sh

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $dir

# startup neo4j and mongo
ttab -t 'shindig-app-dev' eval "\
m4j stop; \
m4j start; \
meteor --settings settings.dev.json --port 3000"

open -a "Google Chrome" http://localhost:3000/
