#!/bin/sh

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $dir

# startup neo4j and mongo
ttab -t 'shindig-ios-stage' eval "\
MONGO_URL=mongodb://mongo:[PASSWORD]@[IP]:27017/shindig-app \
meteor run ios --settings settings.stage.json --port 3000"