#!/bin/sh

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $dir

ttab -t 'shindig-app-stage' eval "\
MONGO_URL=mongodb://mongo:[PASSWORD]@[IP]:27017/shindig-app \
meteor --settings settings.stage.json --port 3000"

open -a "Google Chrome" http://localhost:3000/
